# 指定语言环境
language: node_js
# 指定需要sudo权限
sudo: required
# 指定node_js版本
node_js: 
  - 9.7.1
# 指定缓存模块，可选。缓存可加快编译速度。
notifications:
  email:
    recipients:
      - zbrightz@163.com
    on_success: change # default: change
    on_failure: always # default: always
cache:
  directories:
    - node_modules

before_install:
  - npm install -g hexo-cli

# Start: Build Lifecycle
install:
  - npm install
  - npm install hexo-deployer-git --save

# 执行清缓存，生成网页操作
script:
  - hexo clean
  - hexo generate
  - cp README.md ./public/README.md
after_script:
  - cd ./public
  - git init
  - git config user.name "brightphone"
  - git config user.email "zbrightz@163.com"
  - git add .
  - git commit -m "Update Blog By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  # Github Pages
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master 
  # Coding Pages
  - git push --force --quiet "https://brightphone:${CO_TOKEN}@${CO_REF}" master:master
  
  - git tag v0.0.$TRAVIS_BUILD_NUMBER -a -m "Auto Taged By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  # Github Pages
  - git push --quiet "https://${GH_TOKEN}@${GH_REF}" master:master --tags
  # Coding Pages
  - git push --quiet "https://brightphone:${CO_TOKEN}@${CO_REF}" master:master --tags
  
global:
   # Github Pages
 - GH_REF: github.com/brightphone/brightphone.github.io
   # Coding Pages
 - CO_REF: git.coding.net/brightphone/brightphone.coding.me.git